# .bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls="exa --icons"
alias la="ls -la"
alias cat="bat --theme=base16 --style=plain --paging=never"
alias tree="ls --tree"
alias g="copier -c github_token 2>&1 > /dev/null && git" # @requires: [copier](https://github.com/AlphaTechnolog/copier)

export PATH="$PATH:$HOME/.local/bin"
PS1='[\u@\h \W]\$ '
. "$HOME/.cargo/env"

eval "$(starship init bash)"
