#!/usr/bin/env bash

# +-----------------------------------------------------------------------------------------------------+
# | the autostart script, just init some programs, feel free to change this to make your own autostart! |
# | but keep some things like how they are in this sample file.                                         |
# +-----------------------------------------------------------------------------------------------------+

conf_path=$HOME/.config/dk

# kill some programs, Please KEEP
kill_progs () {
  declare -a progs=('eww' 'picom' 'dunst' 'sxhkd')
  for prog in ${progs[@]}; do
    if pgrep -x $prog; then
      pkill $prog
    fi
  done
}

kill_progs

# wallpaper setup. Keep
find_wallpaper () {
  local tiled=$conf_path/tile.png

  if ! test -f $tiled; then
    declare -a choices=('wallpaper.jpg' 'wallpaper.png' 'wallpaper.svg')
    for choice in ${choices[@]}; do
      if test -f $conf_path/$choice; then
        echo $choice
        return 0
      fi
    done

    return 1
  else
    echo tile.png
    return 0
  fi
}

get_basename () {
  local name=$1

  echo $(echo $name | sed 's/\./ /g' | awk '{print $1}')
}

if find_wallpaper; then
  wallpaper=$(find_wallpaper)
  if [[ $(get_basename $wallpaper) != 'tile' ]]; then
    feh --bg-scale $conf_path/$wallpaper
  else
    feh --bg-tile $conf_path/$wallpaper
  fi
fi

# compositor (picom). Keep, this makes eww bars work right
picom --config=$conf_path/picom.conf -b

# eww setup. Keep (pls)
eww_conf=$conf_path/eww
eww_bin=/usr/bin/eww # change if you want

function eww () {
  ${eww_bin} -c $eww_conf ${@}
}

# spawning eww daemon and opening eww bar
eww daemon
eww open bar

# keybindings, keep
sxhkd -c $conf_path/sxhkdrc &

# restore redshift state
$conf_path/eww/scripts/redshift restore

# +------------------------------------------------------------------------------------+
# | starting from this comment, you can start adding/removing the stuff that you want! |
# +------------------------------------------------------------------------------------+

# loads ~/.Xresources (also apply appearance settings to st), I recommend to keep this, but if you want to
# remove, it's ok, nothing will break, st will load the default appearance settings
xrdb merge ~/.Xresources

# notifications daemon, dunst: i included config, but you can switch to another if you want ofc!
dunst &
