#!/bin/bash

# launcher
super + shift + Return
  rofi -show drun

# terminal
super + Return
  st

# browser
super + b
  firefox

# dedicated volume keys
{XF86AudioRaiseVolume,XF86AudioLowerVolume}
	pamixer {-i,-d} 2

# dedicated backlight keys
{XF86MonBrightnessUp,XF86MonBrightnessDown}
	xbacklight {+10,-10}

# reload sxhkd
super + Escape
	pkill -USR1 -x sxhkd

# quit dk
super + shift + {q,r}
  dkcmd {exit,reload}

# restart dk
super + shift + r
	dkcmd restart

# focus next or previous window
super + {j,k}
	dkcmd win focus {next,prev}

# kill window
super + w
  dkcmd win kill

# toggle fullscreen and fake fullscreen
super + f
  dkcmd win full

# toggle floating or sticky
super + space
	dkcmd win float

# move window, signed (+/-) for relative changes
super + shift + {j,k}
	dkcmd win resize {y=+20,y=-20}

# resize window, signed (+/-) for relative changes
super + {h,l}
	dkcmd win resize {w=-50,w=+50}

# view, send, or follow to a workspace (by number)
super + {_,shift + ,ctrl + }{1-6}
	dkcmd ws {view,send,follow} {1-6}

# view, send, or follow to the next, previous, last active,
# next non-empty, or prev non-empty workspace
super + {_,shift + ,ctrl + }{bracketleft,bracketright,BackSpace,Left,Right}
	dkcmd ws {view,send,follow} {prev,next,last,prevne,nextne}

# view, send, or follow to the next, previous, or last active monitor
super + {_,shift + ,ctrl + }{comma,period,backslash}
	dkcmd mon {view,send,follow} {prev,next,last}

# jgmenu
~button3
  xqp 0 $(xdo id -N "" -n root) && ~/.config/dk/jgmenu/run
