#!/bin/bash

# base
_DARKER_BG=#13171b
_BG=#171B20
_CONTRAST_BG=#1a1e24
_LIGHTER_BG=#21262e
_FG=#b6beca

# --colors--

# black
_BLACK=#242931
_LIGHT_BLACK=#485263

# red
_RED=#e05f65
_LIGHT_RED=#e05f65

# green
_GREEN=#94F7C5
_LIGHT_GREEN=#94F7C5

# yellow
_YELLOW=#f1cf8a
_LIGHT_YELLOW=#f1cf8a

# blue
_BLUE=#70a5eb
_LIGHT_BLUE=#70a5eb

# magenta
_MAGENTA=#c68aee
_LIGHT_MAGENTA=#c68aee

# cyan
_CYAN=#74bee9
_LIGHT_CYAN=#74bee9

# white
_WHITE=#dee1e6
_LIGHT_WHITE=#dee1e6

# ---- misc -----

_WALLPAPER=$HOME/.config/themes/wallpapers/circuits.jpg
