require "configuration.theme"
require "configuration.layouts"
require "configuration.mousebindings"
require "configuration.keybindings"
require "configuration.rules"
require "configuration.autofocus"
require "configuration.floating-clients"
require "configuration.monitor"
require 'configuration.music-notification'
